#!/usr/bin/env node
// REST → SOAP bridge generated by the Vizroute SOAP Migration Workbench.
// Every route in bridge.json is served: the JSON request becomes the SOAP
// envelope, the SOAP answer becomes JSON. Node 18+, no dependencies.
//
//   node adapter.mjs                 # serves bridge.json on http://localhost:8080
//   node adapter.mjs --port 9090 --soap https://other-host/Service.svc
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const SOAP11 = "http://schemas.xmlsoap.org/soap/envelope/";
const SOAP12 = "http://www.w3.org/2003/05/soap-envelope";
const XSI = "http://www.w3.org/2001/XMLSchema-instance";

// ─── XML ────────────────────────────────────

const escapeXml = (v) => String(v ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/** A small XML reader: { name, ns, attrs, children, text } with namespaces resolved. */
const parseXml = (input) => {
  const root = { name: "#doc", children: [], nsMap: {} };
  const stack = [root];
  const decode = (s) => s.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&#(x[0-9a-fA-F]+|\d+);/g, (m, c) => String.fromCodePoint(c[0] === "x" ? parseInt(c.slice(1), 16) : parseInt(c, 10))).replace(/&amp;/g, "&");
  const re = /<!\[CDATA\[([\s\S]*?)\]\]>|<!--[\s\S]*?-->|<\?[\s\S]*?\?>|<!DOCTYPE[^>]*>|<\/([^\s>]+)\s*>|<([^\s/>]+)((?:\s+[^\s=]+\s*=\s*(?:"[^"]*"|'[^']*'))*)\s*(\/?)>|([^<]+)/g;
  let m;
  while ((m = re.exec(input))) {
    const top = stack[stack.length - 1];
    // Groups: 1 CDATA · 2 closing tag name · 3 opening tag name · 4 attributes · 5 self-closing slash · 6 text.
    if (m[1] !== undefined) { top.text = (top.text || "") + m[1]; continue; }
    if (m[6] !== undefined) { if (m[6].trim()) top.text = (top.text || "") + decode(m[6]); continue; }
    if (m[2]) { stack.pop(); continue; }
    if (!m[3]) continue;
    const attrs = {};
    for (const a of m[4].matchAll(/([^\s=]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g)) attrs[a[1]] = decode(a[2] ?? a[3] ?? "");
    const nsMap = { ...top.nsMap };
    for (const [k, v] of Object.entries(attrs)) { if (k === "xmlns") nsMap[""] = v; else if (k.startsWith("xmlns:")) nsMap[k.slice(6)] = v; }
    const at = m[3].indexOf(":");
    const prefix = at === -1 ? "" : m[3].slice(0, at);
    const node = { name: at === -1 ? m[3] : m[3].slice(at + 1), ns: nsMap[prefix] || "", attrs, children: [], text: "", nsMap };
    top.children.push(node);
    if (!m[5]) stack.push(node);
  }
  return root.children[0] || null;
};

const isNil = (node) => Object.entries(node.attrs).some(([k, v]) => k.endsWith(":nil") && v === "true");

// ─── Schema helpers ─────────────────────────

const makeSchemaTools = (schemas) => {
  const resolve = (schema, seen = new Set()) => {
    let s = schema;
    while (s && s.$ref) {
      const name = s.$ref.split("/").pop();
      if (seen.has(name)) return null;
      seen.add(name);
      s = schemas[name];
    }
    if (s && s.allOf && !s.properties) {
      const merged = { type: "object", properties: {}, required: [], "x-xml": {} };
      for (const part of s.allOf) {
        const r = resolve(part, new Set(seen));
        if (!r) continue;
        Object.assign(merged.properties, r.properties || {});
        merged.required.push(...(r.required || []));
        Object.assign(merged["x-xml"], r["x-xml"] || {});
      }
      return merged;
    }
    return s || null;
  };

  /** JSON value → XML text for one element, following the schema's property order. */
  const toXml = (value, schema, name, ns, parentNs, indent) => {
    const s = resolve(schema) || {};
    const pad = "  ".repeat(indent);
    const open = (attrs = {}, selfClose = false, inner = "") => {
      const nsDecl = ns !== parentNs ? ` xmlns="${escapeXml(ns)}"` : "";
      const a = Object.entries(attrs).map(([k, v]) => ` ${k}="${escapeXml(v)}"`).join("");
      return selfClose ? `<${name}${nsDecl}${a}/>` : `<${name}${nsDecl}${a}>${inner}</${name}>`;
    };
    if (value === null || value === undefined) return `${pad}${open({ "xsi:nil": "true" }, true)}`;
    if (Array.isArray(value)) return value.map((item) => toXml(item, s.items || {}, name, ns, parentNs, indent)).join("\n");
    if (typeof value === "object") {
      const xml = s["x-xml"] || {};
      const props = s.properties || {};
      const attrs = {};
      let text = null;
      const children = [];
      // Schema order first (XML sequences are ordered), then anything the schema does not know.
      const order = [...Object.keys(props), ...Object.keys(value).filter((k) => !(k in props))];
      for (const prop of order) {
        if (!(prop in value)) continue;
        const info = xml[prop] || { name: prop, ns: "" };
        if (info.attribute) attrs[info.name] = value[prop];
        else if (info.text) text = value[prop];
        else children.push(toXml(value[prop], props[prop] || {}, info.name, info.ns || "", ns, indent + 1));
      }
      if (text !== null && !children.length) return `${pad}${open(attrs, false, escapeXml(text))}`;
      if (!children.length) return `${pad}${open(attrs, true)}`;
      return `${pad}${open(attrs, false, `\n${children.join("\n")}\n${pad}`)}`;
    }
    return `${pad}${open({}, false, escapeXml(value))}`;
  };

  const coerce = (text, schema) => {
    const s = resolve(schema) || {};
    if (s.type === "integer" || s.type === "number") { const n = Number(text); return Number.isFinite(n) && text.trim() !== "" ? n : text; }
    if (s.type === "boolean") return text.trim() === "true" || text.trim() === "1";
    return text;
  };

  /** XML element → JSON, named and typed by the schema; unknown children are kept as text. */
  const fromXml = (node, schema) => {
    if (!node) return null;
    if (isNil(node)) return null;
    const s = resolve(schema) || {};
    if (s.type === "array") return node.children.length ? node.children.map((c) => fromXml(c, s.items)) : (node.text ? [coerce(node.text, s.items)] : []);
    const props = s.properties || {};
    if (!Object.keys(props).length) {
      if (!node.children.length) return coerce(node.text, s);
      const out = {};
      for (const c of node.children) {
        const v = fromXml(c, {});
        out[c.name] = c.name in out ? [].concat(out[c.name], [v]) : v;
      }
      return out;
    }
    const xml = s["x-xml"] || {};
    const out = {};
    for (const [prop, ps] of Object.entries(props)) {
      const info = xml[prop] || { name: prop };
      if (info.attribute) { if (info.name in node.attrs) out[prop] = coerce(node.attrs[info.name], ps); continue; }
      if (info.text) { out[prop] = coerce(node.text, ps); continue; }
      const matches = node.children.filter((c) => c.name === info.name);
      const target = resolve(ps) || {};
      if (target.type === "array") { if (matches.length) out[prop] = matches.map((c) => fromXml(c, target.items)); continue; }
      if (matches.length) out[prop] = fromXml(matches[0], ps);
    }
    return out;
  };

  return { resolve, toXml, fromXml, coerce };
};

// ─── The adapter ────────────────────────────

const matchPath = (template, path) => {
  const t = template.split("/").filter(Boolean);
  const p = path.split("/").filter(Boolean);
  if (t.length !== p.length) return null;
  const params = {};
  for (let i = 0; i < t.length; i++) {
    if (t[i].startsWith("{") && t[i].endsWith("}")) params[t[i].slice(1, -1)] = decodeURIComponent(p[i]);
    else if (t[i] !== p[i]) return null;
  }
  return params;
};

const problem = (status, title, detail, type = "about:blank") => ({ status, body: { type, title, status, detail } });

const readBody = (req) => new Promise((resolve, reject) => {
  const chunks = [];
  req.on("data", (c) => chunks.push(c));
  req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
  req.on("error", reject);
});

export const createAdapter = (bridge, { soapUrl = "", fetchImpl = fetch, log = () => {} } = {}) => {
  const tools = makeSchemaTools(bridge.schemas || {});
  const routes = bridge.routes || [];

  const call = async (route, fields) => {
    const version = route.soapVersion || bridge.soap.version || "1.1";
    const envNs = version === "1.2" ? SOAP12 : SOAP11;
    const schema = route.request.inline || (route.request.schema ? { $ref: `#/components/schemas/${route.request.schema}` } : {});
    const body = route.request.element ? tools.toXml(fields, schema, route.request.element, route.request.namespace, "", 2) : "";
    const envelope = `<?xml version="1.0" encoding="utf-8"?>\n<soapenv:Envelope xmlns:soapenv="${envNs}" xmlns:xsi="${XSI}">\n  <soapenv:Header/>\n  <soapenv:Body>\n${body}\n  </soapenv:Body>\n</soapenv:Envelope>`;
    const headers = version === "1.2"
      ? { "Content-Type": `application/soap+xml; charset=utf-8${route.soapAction ? `; action="${route.soapAction}"` : ""}` }
      : { "Content-Type": "text/xml; charset=utf-8", SOAPAction: `"${route.soapAction || ""}"` };
    const url = soapUrl || route.endpoint || bridge.soap.url;
    if (!url) return problem(502, "No SOAP endpoint", "The WSDL declares no address; start the adapter with --soap <url>.");
    let res;
    let text;
    try {
      res = await fetchImpl(url, { method: "POST", headers, body: envelope });
      text = await res.text();
    } catch (e) {
      return problem(502, "SOAP service unreachable", `${url}: ${e.message}`);
    }
    log(`${route.operation} → ${url} ${res.status}`);
    const doc = text.trim() ? parseXml(text) : null;
    const bodyNode = doc?.children.find((c) => c.name === "Body") || null;
    const first = bodyNode?.children[0] || null;
    if (!doc || !bodyNode) {
      return problem(502, "Not a SOAP response", `The service answered ${res.status} with ${text.slice(0, 200) || "an empty body"}`);
    }
    if (first && first.name === "Fault") {
      const get = (n) => first.children.find((c) => c.name === n) || null;
      const code = get("faultcode")?.text || get("Code")?.children.find((c) => c.name === "Value")?.text || "";
      const reason = get("faultstring")?.text || get("Reason")?.children.find((c) => c.name === "Text")?.text || "SOAP fault";
      const detail = get("detail") || get("Detail");
      const detailName = detail?.children[0]?.name || "";
      const known = route.faults.find((f) => f.name === detailName) || route.faults.find((f) => reason.includes(f.name) || code.includes(f.name));
      // An unmapped fault: the SOAP fault code still says whose fault it was (Client/Sender → 400).
      const clientFault = /(^|:)(Client|Sender)$/.test(code.trim());
      const status = known ? known.status : clientFault ? 400 : 500;
      const title = known ? known.reason : clientFault ? "Bad Request" : "Internal Server Error";
      return { status, body: { type: `urn:soap-fault:${detailName || code || "unknown"}`, title, status, detail: reason, ...(detail ? { soapDetail: tools.fromXml(detail.children[0] || detail, {}) } : {}) } };
    }
    if (route.response.oneWay || (!first && route.response.status === 202)) return { status: 202, body: null };
    if (!first) return { status: route.response.status === 204 ? 204 : 204, body: null };
    const responseSchema = route.response.inline || (route.response.schema ? { $ref: `#/components/schemas/${route.response.schema}` } : {});
    let json = tools.fromXml(first, responseSchema);
    if (route.response.unwrap && json && typeof json === "object" && route.response.unwrap in json) json = json[route.response.unwrap];
    if (route.response.status === 204) return { status: 204, body: null };
    return { status: route.response.status, body: json === undefined ? null : json };
  };

  const handle = async (req, pathOverride) => {
    const url = new URL(pathOverride ?? req.url, "http://localhost");
    if (req.method === "OPTIONS") return { status: 204, body: null };
    if (url.pathname === "/" || url.pathname === "/__routes") {
      return { status: 200, body: { service: bridge.service, soap: soapUrl || bridge.soap.url, routes: routes.map((r) => `${r.method} ${r.path}`) } };
    }
    let route = null;
    let params = null;
    let pathMatched = false;
    for (const r of routes) {
      const p = matchPath(r.path, url.pathname);
      if (!p) continue;
      pathMatched = true;
      if (r.method === req.method) { route = r; params = p; break; }
    }
    if (!route) return pathMatched ? problem(405, "Method Not Allowed", `${url.pathname} exists but not for ${req.method}.`) : problem(404, "Not Found", `No route for ${req.method} ${url.pathname}. GET /__routes lists them.`);

    const fields = {};
    const requestSchema = tools.resolve(route.request.inline || (route.request.schema ? { $ref: `#/components/schemas/${route.request.schema}` } : {})) || {};
    const propSchema = (field) => requestSchema.properties?.[field] || {};
    for (const p of route.pathParams) fields[p.field] = tools.coerce(params[p.name] ?? "", propSchema(p.field));
    for (const q of route.queryParams) {
      const v = url.searchParams.get(q.name);
      if (v !== null) fields[q.field] = tools.coerce(v, propSchema(q.field));
      else if (q.required) return problem(400, "Bad Request", `Query parameter "${q.name}" is required.`);
    }
    if (route.hasBody) {
      const raw = await readBody(req);
      if (raw.trim()) {
        let parsed;
        try { parsed = JSON.parse(raw); } catch (e) { return problem(400, "Bad Request", `The body is not valid JSON: ${e.message}`); }
        if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return problem(400, "Bad Request", "The body must be a JSON object.");
        Object.assign(fields, parsed);
      }
      for (const required of requestSchema.required || []) {
        if (!(required in fields)) return problem(400, "Bad Request", `"${required}" is required.`);
      }
    }
    return call(route, fields);
  };

  /** Answer one HTTP exchange; `pathOverride` lets a host mount the adapter under a prefix. */
  const respond = async (req, res, pathOverride) => {
    let out;
    try {
      out = await handle(req, pathOverride);
    } catch (e) {
      out = problem(500, "Adapter error", e.message);
    }
    const isProblem = out.body && typeof out.body === "object" && "title" in out.body && "status" in out.body && out.status >= 400;
    res.writeHead(out.status, {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET,POST,PUT,PATCH,DELETE,OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
      ...(out.body === null || out.body === undefined ? {} : { "Content-Type": isProblem ? "application/problem+json" : "application/json" }),
    });
    res.end(out.body === null || out.body === undefined ? undefined : JSON.stringify(out.body));
  };
  const server = createServer((req, res) => respond(req, res));
  return { server, respond, handle, call, routes };
};

// Run as a program: node adapter.mjs [--port 8080] [--soap url] [--bridge bridge.json]
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const args = process.argv.slice(2);
  const flag = (n, d) => { const i = args.indexOf(n); return i === -1 ? d : args[i + 1]; };
  const here = dirname(fileURLToPath(import.meta.url));
  const bridgePath = flag("--bridge", join(here, "bridge.json"));
  let bridge;
  try {
    bridge = JSON.parse(await readFile(bridgePath, "utf8"));
  } catch (e) {
    console.error(e.code === "ENOENT" ? `bridge.json not found at ${bridgePath}. Keep adapter.mjs and bridge.json in the same folder (both are in the ZIP), or pass --bridge <path>.` : `bridge.json could not be read: ${e.message}`);
    process.exit(1);
  }
  if (bridge?.vizroute !== "soap-bridge" || !Array.isArray(bridge.routes)) {
    console.error(`${bridgePath} is not a bridge file produced by the workbench.`);
    process.exit(1);
  }
  const port = Number(flag("--port", "8080"));
  const { server, routes } = createAdapter(bridge, { soapUrl: flag("--soap", ""), log: (line) => console.log(line) });
  server.on("error", (e) => {
    console.error(e.code === "EADDRINUSE" ? `Port ${port} is already in use. Stop the other program or start with --port <number> (and use that port in the URL).` : `Could not start: ${e.message}`);
    process.exit(1);
  });
  server.listen(port, () => {
    console.log(`${bridge.service}: REST adapter on http://localhost:${port} → SOAP ${flag("--soap", "") || bridge.soap.url}`);
    for (const r of routes) console.log(`  ${r.method.padEnd(6)} ${r.path}  ←  ${r.operation}`);
  });
}
