import { useState, useMemo } from "react";
import {
  ArrowLeft, FileText, Download, Copy, Check, Eye, Code,
  ChevronDown, Globe, Lock, BookOpen,
} from "lucide-react";
import { HTTP_METHODS } from "../utils/constants";

const METHOD_COLOR = { GET: "#34d399", POST: "#fbbf24", PUT: "#60a5fa", PATCH: "#a78bfa", DELETE: "#f87171" };

// The preview is a preview. A 1,671-operation spec renders roughly a
// hundred thousand elements if every parameter table is mounted at once,
// while the downloads and the copy button always carry the whole document.
const PREVIEW_GROUPS = 12;
const PREVIEW_TEXT_CHARS = 200_000;

const extractDocs = (data) => {
  if (!data) return null;
  const doc = { title: "", version: "", description: "", baseUrl: "", groups: [] };
  if (data.openapi || data.swagger) {
    doc.title = data.info?.title || "API";
    doc.version = data.info?.version || "";
    doc.description = data.info?.description || "";
    doc.baseUrl = data.servers?.[0]?.url || (data.host ? `${data.schemes?.[0] || "https"}://${data.host}${data.basePath || ""}` : "");
    const tagGroups = {};
    Object.entries(data.paths || {}).forEach(([path, obj]) => {
      HTTP_METHODS.forEach((m) => {
        const op = obj?.[m]; if (!op) return;
        const tags = op.tags?.length ? op.tags : ["Default"];
        tags.forEach((tag) => {
          if (!tagGroups[tag]) tagGroups[tag] = [];
          let bodyExample = null;
          if (op.requestBody?.content?.["application/json"]?.schema?.properties) {
            bodyExample = {};
            Object.entries(op.requestBody.content["application/json"].schema.properties).forEach(([k, v]) => {
              bodyExample[k] = v.example || v.default || (v.type === "string" ? "string" : v.type === "integer" ? 0 : v.type === "boolean" ? false : null);
            });
          }
          tagGroups[tag].push({ method: m.toUpperCase(), path, name: op.summary || op.operationId || `${m.toUpperCase()} ${path}`, description: op.description || "", params: op.parameters || [], bodyExample, deprecated: !!op.deprecated });
        });
      });
    });
    doc.groups = Object.entries(tagGroups).map(([name, endpoints]) => ({ name, endpoints }));
  } else if (data.info && data.item) {
    doc.title = data.info.name || "API Collection";
    doc.version = data.info.version || "";
    const walk = (items, groupName) => {
      const group = { name: groupName, endpoints: [] };
      items.forEach((i) => {
        if (i.item) { doc.groups.push(...[{ name: i.name, endpoints: [] }]); walk(i.item, i.name); return; }
        const req = i.request || i;
        const url = typeof req.url === "string" ? req.url : req.url?.raw || "";
        const existing = doc.groups.find((g) => g.name === groupName);
        (existing || group).endpoints.push({ method: (req.method || "GET").toUpperCase(), path: url, name: i.name, description: i.description?.content || "", params: [], bodyExample: null, deprecated: false });
      });
      if (!doc.groups.find((g) => g.name === groupName) && group.endpoints.length) doc.groups.push(group);
    };
    walk(data.item, "General");
  }
  return doc;
};

const generateMarkdown = (doc) => {
  let md = `# ${doc.title}\n\n`;
  if (doc.version) md += `**Version:** ${doc.version}  \n`;
  if (doc.baseUrl) md += `**Base URL:** \`${doc.baseUrl}\`  \n`;
  if (doc.description) md += `\n${doc.description}\n`;
  md += `\n---\n\n`;
  doc.groups.forEach((group) => {
    md += `## ${group.name}\n\n`;
    group.endpoints.forEach((ep) => {
      md += `### ${ep.deprecated ? "~~" : ""}${ep.method} ${ep.path}${ep.deprecated ? "~~ *(deprecated)*" : ""}\n\n`;
      if (ep.name && ep.name !== `${ep.method} ${ep.path}`) md += `**${ep.name}**\n\n`;
      if (ep.description) md += `${ep.description}\n\n`;
      if (ep.params.length) {
        md += `#### Parameters\n\n| Name | In | Required | Type |\n|------|----|----------|------|\n`;
        ep.params.forEach((p) => { md += `| ${p.name} | ${p.in} | ${p.required ? "Yes" : "No"} | ${p.schema?.type || "-"} |\n`; });
        md += "\n";
      }
      if (ep.bodyExample) {
        md += `#### Request Body\n\n\`\`\`json\n${JSON.stringify(ep.bodyExample, null, 2)}\n\`\`\`\n\n`;
      }
      md += `---\n\n`;
    });
  });
  md += `\n*Generated by Vizroute Doc Generator*\n`;
  return md;
};

const generateHTML = (doc) => {
  let html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${doc.title} — API Docs</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Inter,system-ui,sans-serif;background:#080b12;color:#f8f9fe;line-height:1.6;padding:2rem}
.container{max-width:900px;margin:0 auto}h1{font-size:2rem;margin-bottom:0.5rem;color:#a855f7}h2{font-size:1.4rem;margin:2rem 0 1rem;padding-bottom:0.5rem;border-bottom:1px solid #222a3933}
h3{font-size:1rem;margin:1.5rem 0 0.5rem}.meta{color:#6f7788;font-size:0.85rem;margin-bottom:1rem}
.method{display:inline-block;padding:2px 8px;border-radius:4px;font-size:0.7rem;font-weight:700;margin-right:8px;text-transform:uppercase}
.GET{background:#34d39920;color:#34d399}.POST{background:#fbbf2420;color:#fbbf24}.PUT{background:#60a5fa20;color:#60a5fa}
.PATCH{background:#a78bfa20;color:#a78bfa}.DELETE{background:#f8717120;color:#f87171}
.desc{color:#a4acbc;margin:0.5rem 0}code{background:#121824;padding:2px 6px;border-radius:4px;font-size:0.85rem;color:#60a5fa}
pre{background:#0f141d;border:1px solid #222a3933;border-radius:8px;padding:1rem;overflow-x:auto;margin:0.5rem 0;font-size:0.8rem;color:#a4acbc}
table{width:100%;border-collapse:collapse;margin:0.5rem 0}th,td{text-align:left;padding:6px 12px;border-bottom:1px solid #222a3922;font-size:0.8rem}
th{color:#a4acbc;font-weight:600;text-transform:uppercase;font-size:0.7rem;letter-spacing:0.05em}hr{border:none;border-top:1px solid #222a3922;margin:1.5rem 0}
.deprecated{text-decoration:line-through;opacity:0.5}.footer{margin-top:3rem;text-align:center;color:#222a39;font-size:0.75rem}</style></head><body><div class="container">`;
  html += `<h1>${doc.title}</h1>`;
  if (doc.version || doc.baseUrl) html += `<p class="meta">${doc.version ? `Version ${doc.version}` : ""}${doc.version && doc.baseUrl ? " · " : ""}${doc.baseUrl ? `Base URL: <code>${doc.baseUrl}</code>` : ""}</p>`;
  if (doc.description) html += `<p class="desc">${doc.description}</p>`;
  doc.groups.forEach((group) => {
    html += `<h2>${group.name}</h2>`;
    group.endpoints.forEach((ep) => {
      html += `<h3 ${ep.deprecated ? 'class="deprecated"' : ""}><span class="method ${ep.method}">${ep.method}</span><code>${ep.path}</code></h3>`;
      if (ep.name) html += `<p><strong>${ep.name}</strong></p>`;
      if (ep.description) html += `<p class="desc">${ep.description}</p>`;
      if (ep.params.length) {
        html += `<table><thead><tr><th>Name</th><th>In</th><th>Required</th><th>Type</th></tr></thead><tbody>`;
        ep.params.forEach((p) => { html += `<tr><td><code>${p.name}</code></td><td>${p.in}</td><td>${p.required ? "Yes" : "No"}</td><td>${p.schema?.type || "-"}</td></tr>`; });
        html += `</tbody></table>`;
      }
      if (ep.bodyExample) html += `<pre>${JSON.stringify(ep.bodyExample, null, 2)}</pre>`;
      html += `<hr>`;
    });
  });
  html += `<p class="footer">Generated by Vizroute Doc Generator</p></div></body></html>`;
  return html;
};

const DocGenerator = ({ collection, onBack }) => {
  const [format, setFormat] = useState("preview"); // preview | markdown | html
  const [copied, setCopied] = useState(false);
  const [groupLimit, setGroupLimit] = useState(PREVIEW_GROUPS);

  const doc = useMemo(() => extractDocs(collection), [collection]);
  const markdown = useMemo(() => doc ? generateMarkdown(doc) : "", [doc]);
  const htmlContent = useMemo(() => doc ? generateHTML(doc) : "", [doc]);

  const rawText = format === "html" ? htmlContent : markdown;
  const rawPreview = useMemo(
    () =>
      rawText.length > PREVIEW_TEXT_CHARS
        ? `${rawText.slice(0, PREVIEW_TEXT_CHARS)}${String.fromCharCode(10)}… ${(rawText.length - PREVIEW_TEXT_CHARS).toLocaleString()} more characters — use the download buttons for the full document.`
        : rawText,
    [rawText],
  );
  const totalEndpoints = useMemo(
    () => (doc ? doc.groups.reduce((n, g) => n + g.endpoints.length, 0) : 0),
    [doc],
  );

  const downloadFile = (content, filename, mime) => {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = filename; a.click();
    URL.revokeObjectURL(url);
  };

  const copyContent = () => {
    navigator.clipboard.writeText(format === "html" ? htmlContent : markdown);
    setCopied(true); setTimeout(() => setCopied(false), 2000);
  };

  if (!doc) return (
    <div className="flex-1 flex items-center justify-center"><p className="text-[#6f7788]">Load an API spec first to generate documentation.</p></div>
  );

  return (
    <div className="fixed inset-0 z-50 flex flex-col" style={{ background: "rgba(12,14,18,0.98)", animation: "fadeIn 0.2s ease-out both" }}>
      {/* Header */}
      <div className="px-6 py-4 border-b border-[#222a39]/20 flex items-center gap-4 flex-shrink-0">
        <button onClick={onBack} className="p-2 hover:bg-[#121824] rounded-lg text-[#a4acbc] hover:text-white transition-all group">
          <ArrowLeft size={18} className="group-hover:-translate-x-0.5 transition-transform" />
        </button>
        <div className="flex items-center gap-2">
          <BookOpen size={18} className="text-[#a855f7]" />
          <h2 className="font-bold text-white text-lg">Documentation Generator</h2>
        </div>

        {/* Format tabs */}
        <div className="flex items-center gap-1 bg-[#121824]/40 border border-[#222a39]/20 rounded-lg p-1 ml-4">
          {[{ id: "preview", icon: Eye, label: "Preview" }, { id: "markdown", icon: FileText, label: "Markdown" }, { id: "html", icon: Code, label: "HTML" }].map(({ id, icon: Icon, label }) => (
            <button key={id} onClick={() => setFormat(id)}
              className={`px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded flex items-center gap-1.5 transition-all ${format === id ? "bg-[#a855f7]/15 text-[#a855f7]" : "text-[#6f7788] hover:text-[#a4acbc]"}`}>
              <Icon size={12} /> {label}
            </button>
          ))}
        </div>

        <div className="flex items-center gap-2 ml-auto">
          <button onClick={copyContent} className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-bold text-[#a4acbc] hover:text-white hover:bg-[#121824] border border-[#222a39]/20 transition-all">
            {copied ? <><Check size={12} className="text-[#60a5fa]" /> Copied!</> : <><Copy size={12} /> Copy</>}
          </button>
          <button onClick={() => downloadFile(markdown, `${doc.title.replace(/\s+/g, "-").toLowerCase()}-docs.md`, "text/markdown")}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-bold text-[#a4acbc] hover:text-white hover:bg-[#121824] border border-[#222a39]/20 transition-all">
            <Download size={12} /> .md
          </button>
          <button onClick={() => downloadFile(htmlContent, `${doc.title.replace(/\s+/g, "-").toLowerCase()}-docs.html`, "text/html")}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-bold text-[#080b12] bg-[#a855f7] hover:bg-[#c45cff] transition-all active:scale-[0.97]">
            <Download size={12} /> .html
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto">
        {format === "preview" ? (
          <div className="max-w-4xl mx-auto p-8">
            <h1 className="text-3xl font-extrabold text-white mb-2">{doc.title}</h1>
            <div className="flex items-center gap-3 text-sm text-[#6f7788] mb-4">
              {doc.version && <span className="px-2 py-0.5 bg-[#121824] border border-[#222a39]/20 rounded font-mono text-xs">{doc.version}</span>}
              {doc.baseUrl && <span className="font-mono text-xs text-[#60a5fa]">{doc.baseUrl}</span>}
            </div>
            {doc.description && <p className="text-[#a4acbc] mb-6 leading-relaxed">{doc.description}</p>}
            {doc.groups.slice(0, groupLimit).map((group) => (
              <div key={group.name} className="mb-8">
                <h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-[#222a39]/20">{group.name}</h2>
                {group.endpoints.map((ep, i) => (
                  <div key={`${ep.method}-${ep.path}-${i}`} className={`mb-4 p-4 rounded-xl border border-[#222a39]/15 bg-[#0f141d]/30 ${ep.deprecated ? "opacity-50" : ""}`}>
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-xs font-bold px-2.5 py-0.5 rounded-full uppercase" style={{ background: `${METHOD_COLOR[ep.method] || "#a4acbc"}20`, color: METHOD_COLOR[ep.method] || "#a4acbc" }}>{ep.method}</span>
                      <code className="text-sm text-[#60a5fa] font-mono">{ep.path}</code>
                      {ep.deprecated && <span className="text-[10px] text-[#f43f5e] uppercase font-bold">deprecated</span>}
                    </div>
                    {ep.name && <p className="text-sm font-semibold text-white mb-1">{ep.name}</p>}
                    {ep.description && <p className="text-xs text-[#a4acbc] leading-relaxed">{ep.description}</p>}
                    {ep.params.length > 0 && (
                      <div className="mt-3 overflow-x-auto">
                        <table className="w-full text-xs">
                          <thead><tr className="text-[#6f7788]"><th className="text-left p-1.5 font-bold uppercase tracking-wider text-[10px]">Param</th><th className="text-left p-1.5 font-bold uppercase tracking-wider text-[10px]">In</th><th className="text-left p-1.5 font-bold uppercase tracking-wider text-[10px]">Required</th><th className="text-left p-1.5 font-bold uppercase tracking-wider text-[10px]">Type</th></tr></thead>
                          <tbody>{ep.params.map((p, pi) => (<tr key={pi} className="border-t border-[#222a39]/10"><td className="p-1.5 font-mono text-[#a855f7]">{p.name}</td><td className="p-1.5 text-[#a4acbc]">{p.in}</td><td className="p-1.5">{p.required ? <span className="text-[#f43f5e]">Yes</span> : <span className="text-[#222a39]">No</span>}</td><td className="p-1.5 text-[#6f7788] font-mono">{p.schema?.type || "-"}</td></tr>))}</tbody>
                        </table>
                      </div>
                    )}
                    {ep.bodyExample && (
                      <pre className="mt-3 bg-[#080b12] border border-[#222a39]/15 rounded-lg p-3 text-[10px] font-mono text-[#a4acbc] overflow-auto">{JSON.stringify(ep.bodyExample, null, 2)}</pre>
                    )}
                  </div>
                ))}
              </div>
            ))}

            {doc.groups.length > groupLimit && (
              <button
                onClick={() => setGroupLimit((n) => n + PREVIEW_GROUPS)}
                className="w-full rounded-xl border border-[#222a39]/25 py-3 text-sm text-[#a4acbc] hover:text-white hover:bg-[#121824] transition-colors"
              >
                Show more — {groupLimit.toLocaleString()} of{" "}
                {doc.groups.length.toLocaleString()} groups shown
                {totalEndpoints > 0 && `, ${totalEndpoints.toLocaleString()} endpoints in the download`}
              </button>
            )}
          </div>
        ) : (
          <pre className="p-8 font-mono text-xs text-[#a4acbc] whitespace-pre-wrap break-words leading-relaxed">
            {rawPreview}
          </pre>
        )}
      </div>
    </div>
  );
};

export default DocGenerator;
